find_package(PkgConfig)
pkg_check_modules(PC_AVUTIL libavutil)

find_path(AVUTIL_INCLUDE_DIR libavutil/avutil.h HINTS ${PC_AVUTIL_INCLUDEDIR} ${PC_AVUTIL_INCLUDE_DIRS})
find_library(AVUTIL_LIBRARY avutil HINTS ${PC_AVUTIL_LIBDIR} ${PC_AVUTIL_LIBRARY_DIRS})

SET(AVUTIL_LIBRARIES ${AVUTIL_LIBRARY})
SET(AVUTIL_INCLUDE_DIRS ${AVUTIL_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(AVUTIL DEFAULT_MSG AVUTIL_LIBRARY AVUTIL_INCLUDE_DIR)

mark_as_advanced(AVUTIL_INCLUDE_DIR AVUTIL_LIBRARY)
